### ISSUE TITLE
Doc building on Windows with Visual Studio

### ISSUE THREAD

**Issue by gml16** [Hopson97/open-builder#179]
Thank you for making the doc to build with Visual Studio. I think there are a couple of changes that may improve it:
- There is a typo twice in step 8, "Open `Additional Directories`" should be "Open `Additional Dependencies`".
- When building, error C1083 states: "Cannot open include file: 'server_engine.h': No such file or directory	open-builder"	in `open-builder\src\client\game.h`. 
Including `open-builder\src\server` in step 6 does the trick.
- Other error when building: `C4996 'std::iterator<std::input_iterator_tag,std::pair<sol::object,sol::object>,ptrdiff_t,std::pair<sol::object,sol::object> *,std::pair<sol::object,sol::object> &>': warning STL4015: The std::iterator class template (used as a base class to provide typedefs) is deprecated in C++17.  in	open-builder\deps\sol\sol.hpp:22477`.
From the [Microsoft doc](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-3-c4996) one fix is to add `#pragma warning(disable : 4996)` to sol.hpp or edit the Disable Specific Warnings property to add 4996 in Configuration Properties > C/C++ > Advanced page.

I would happily make a pull request to add those items in the doc if you think they should be added. Especially for point 3, which way do you think is best: adding the pragma line in sol.hpp  or mentioning in the doc to turn off warnings from this error?

**Comment by Hopson97** [comment]
Hi thanks for this, if you could make a PR for these changes that would be amazing :) Point 2 is due to very recent changes, I had just not gotten around to changing the docs yet.

As for point 3, I think go with the `#pragma warning(disable : 4996)`, as this is already being done for a different warning from some other dependency, and it means less steps in the guide which would be easier to follow. 

Thanks!
